# ================================================================= #
#                  CalendarioPlugin Configuration                   #
# ================================================================= #
# This configuration file allows you to customize every aspect of   #
# the Calendario plugin, from time settings to visual effects.      #
# ----------------------------------------------------------------- #

# --- GENERAL SETTINGS ---
# Sets the plugin's language. This corresponds to the file name in 'plugins/CalendarioPlugin/lang/'.
# Included languages: en_US, it_IT.
language: "en_US"

# Set to 'true' to enable debug messages in the console.
debug-mode: false


# --- TIME SETTINGS ---
# Controls the duration of the day/night cycle in real seconds for each season.
# A standard Minecraft day lasts 1200 seconds (600 for day, 600 for night).
time-cycle:
  primavera:
    day-duration-seconds: 600  # 10 minutes
    night-duration-seconds: 600 # 10 minutes
  estate:
    day-duration-seconds: 900  # 15 minutes
    night-duration-seconds: 300 # 5 minutes
  autunno:
    day-duration-seconds: 600  # 10 minutes
    night-duration-seconds: 600 # 10 minutes
  inverno:
    day-duration-seconds: 420  # 7 minutes
    night-duration-seconds: 780 # 13 minutes


# --- SEASONAL RESOURCE PACKS (Vanilla Compatible) ---
# Enter the direct download links and SHA-1 hashes for each resource pack.
# If you don't want to send a pack for a certain season, leave the URL empty ("").
resource-packs:
  primavera:
    url: ""
    sha1: ""
  estate:
    url: ""
    sha1: ""
  autunno:
    url: ""
    sha1: ""
  inverno:
    url: ""
    sha1: ""


# --- SLEEP MECHANICS ---
# Percentage of players (from 0 to 100) required to sleep to skip the night.
# Setting it to 100 means everyone must sleep. Setting it to 50 means only half need to.
# If this option is not present, the default value will be 100.
sleep-mechanics:
  players-sleeping-percentage: 100


# --- VISUAL EFFECTS SETTINGS ---
visual-effects:
  inverno:
    # Probability (0-100) of an attempt to place snow/ice.
    # A higher value means faster freezing.
    freeze-chance: 50
  primavera:
    # Probability of an attempt to melt snow/ice.
    thaw-chance: 35
    # Probability (0-100) of spawning a flower on grass freed from snow.
    flower-spawn-chance: 5


# --- SEASONAL FARMING SETTINGS ---
seasonal-farming:
  # Probability (from 0.0 to 1.0) that an out-of-season plant can grow.
  # 0.25 = 25% chance. 0.0 = growth is completely blocked.
  out-of-season-growth-chance: 0.25


# --- BOSS BAR SETTINGS ---
bossbar:
  # Set to 'false' to completely disable the Boss Bar for everyone.
  enabled: true
  # Set to 'false' to hide the colored progress bar and show only the text.
  show-progress-bar: false
  # Title format. Placeholders: {data}, {stagione}, {meteo}, {ora}
  format: "&a{data} &8| {stagione} &8| {meteo} &8| &e{ora}"
  # Bar color: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
  bar-color: "BLUE"
  # Bar style: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  bar-style: "SOLID"


# ================================================================= #
#      INTERNAL CALENDAR DATA - DO NOT MODIFY MANUALLY              #
# ================================================================= #
calendario:
  anno: 1
  mese: 1
  giorno: 1
  total-ticks-salvati: 0